[project]
name = "fraud-detection-ml-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "kafka-python>=2.0.2",
    "pymongo>=4.13.0",
    "redis>=6.2.0",
    "scikit-learn>=1.6.1",
]
